sudo: required

services:
  - rabbitmq

language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - curl -i -u guest:guest -H "content-type:application/json"     -XPUT -d'{"type":"topic","durable":true}'     http://127.0.0.1:15672/api/exchanges/%2f/eiffel.test

script:
  - ./gradlew test integrationTest --stacktrace

after_success:
- ./gradlew jacocoTestReport coveralls
